# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature', 'feat']

chore:
 - head-branch: ['^chore', 'chore']

bugfix:
  - head-branch: ['^fix', 'fix']
  
# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
documentation:
- changed-files:
  - any-glob-to-any-file: docs/**
  - any-glob-to-any-file: '**/*.md'
  - head-branch: ['doc']


ci:
- changed-files:
  - any-glob-to-any-file: .github/**
