SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';
SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."companhias" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."companhias" OWNER TO "postgres";
ALTER TABLE "public"."companhias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."companhias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."depoimentos" (
    "id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "autor" "text" NOT NULL,
    "avatar" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."depoimentos" OWNER TO "postgres";
ALTER TABLE "public"."depoimentos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."depoimentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."estados" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "sigla" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."estados" OWNER TO "postgres";
ALTER TABLE "public"."estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."passagem" (
    "id" bigint NOT NULL,
    "tipo" "text" NOT NULL,
    "preco_ida" numeric NOT NULL,
    "preco_volta" numeric NOT NULL,
    "taxa_embarque" numeric NOT NULL,
    "conexoes" integer NOT NULL,
    "tempo_voo" integer NOT NULL,
    "origem_id" bigint,
    "destino_id" bigint,
    "companhia_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."passagem" OWNER TO "postgres";
ALTER TABLE "public"."passagem" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."passagem_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."promocoes" (
    "id" bigint NOT NULL,
    "destino" "text" NOT NULL,
    "imagem" "text",
    "preco" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."promocoes" OWNER TO "postgres";
ALTER TABLE "public"."promocoes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."promocoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "nascimento" timestamp without time zone NOT NULL,
    "cpf" "text" NOT NULL,
    "telefone" "text" NOT NULL,
    "email" "text" NOT NULL,
    "senha" "text" NOT NULL,
    "genero" "text",
    "cidade" "text" NOT NULL,
    "estado_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "last_login_at" timestamp with time zone
);
ALTER TABLE "public"."users" OWNER TO "postgres";
ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."companhias" ADD CONSTRAINT "companhias_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."depoimentos" ADD CONSTRAINT "depoimentos_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."estados" ADD CONSTRAINT "estados_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."passagem" ADD CONSTRAINT "passagem_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."promocoes" ADD CONSTRAINT "promocoes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."passagem" ADD CONSTRAINT "passagem_companhia_id_fkey" FOREIGN KEY ("companhia_id") REFERENCES "public"."companhias"("id");
ALTER TABLE ONLY "public"."passagem" ADD CONSTRAINT "passagem_destino_id_fkey" FOREIGN KEY ("destino_id") REFERENCES "public"."estados"("id");
ALTER TABLE ONLY "public"."passagem" ADD CONSTRAINT "passagem_origem_id_fkey" FOREIGN KEY ("origem_id") REFERENCES "public"."estados"("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_estado_id_fkey" FOREIGN KEY ("estado_id") REFERENCES "public"."estados"("id");
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


GRANT ALL ON TABLE "public"."companhias" TO "anon";
GRANT ALL ON TABLE "public"."companhias" TO "authenticated";
GRANT ALL ON TABLE "public"."companhias" TO "service_role";

GRANT ALL ON SEQUENCE "public"."companhias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."companhias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."companhias_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."depoimentos" TO "anon";
GRANT ALL ON TABLE "public"."depoimentos" TO "authenticated";
GRANT ALL ON TABLE "public"."depoimentos" TO "service_role";

GRANT ALL ON SEQUENCE "public"."depoimentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."depoimentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."depoimentos_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."estados" TO "anon";
GRANT ALL ON TABLE "public"."estados" TO "authenticated";
GRANT ALL ON TABLE "public"."estados" TO "service_role";

GRANT ALL ON SEQUENCE "public"."estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."estados_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."passagem" TO "anon";
GRANT ALL ON TABLE "public"."passagem" TO "authenticated";
GRANT ALL ON TABLE "public"."passagem" TO "service_role";

GRANT ALL ON SEQUENCE "public"."passagem_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."passagem_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."passagem_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."promocoes" TO "anon";
GRANT ALL ON TABLE "public"."promocoes" TO "authenticated";
GRANT ALL ON TABLE "public"."promocoes" TO "service_role";

GRANT ALL ON SEQUENCE "public"."promocoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promocoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promocoes_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

drop extension if exists "pg_net";

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();
CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();
CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();
CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();
CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

